language: python
python:
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

services:
  - postgresql

enc:
  - DATABASE_URL='postgres://postgres:postgres@localhost:5432/travis_ci_test'
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# command to run tests
script:
  - python manage.py test --noinput
  - python manage.py migrate --noinput
